language: r
r:
  - devel
sudo: false
cache: packages
bioc_required: true

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "if (!require('knitr')) install.packages('knitr')"
  - Rscript -e "if (!require('mvoutlier')) install.packages('mvoutlier')"
  - Rscript -e "if (!require('bookdown')) devtools::install_github('rstudio/bookdown')"
  - Rscript -e "if (!require('scater')) devtools::install_github('davismcc/scater')"
  - Rscript -e "if (!require('scRNA.seq.funcs')) devtools::install_github('hemberg-lab/scRNA.seq.funcs')"
  - Rscript -e "if (!require('RUVSeq')) {source('https://bioconductor.org/biocLite.R');biocLite('RUVSeq')}"
  - Rscript -e "if (!require('destiny')) {source('https://bioconductor.org/biocLite.R');biocLite('destiny')}"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
