language: r

pandoc_version: 1.17.0.1

r_github_packages:
  - rstudio/bookdown
  - hemberg-lab/scRNA.seq.funcs
  - davismcc/scater

r_packages:
  - mvoutlier
  - knitr

bioc_packages:
  - RUVSeq

install: true

sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_book/_bookdown_files

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
