language: R
sudo: false
cache: packages

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "if (!require('bookdown')) devtools::install_github('rstudio/bookdown')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
