language: r
r:
  - devel
sudo: false
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_book/_bookdown_files

bioc_packages:
  - RUVSeq

r_github_packages:
  - rstudio/bookdown
  - davismcc/scater
  - hemberg-lab/scRNA.seq.funcs

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
